name: CI workflow
on: push
jobs:
  php-cs-fixer:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
    name: Check coding standard
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: php-cs-fixer

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Check coding standard
        run: PHP_CS_FIXER_IGNORE_ENV=1 php-cs-fixer fix --dry-run --diff
